import { GENERATED_CONFIG } from './generated-config.js';

const CONFIG = {
  SUPABASE_URL: GENERATED_CONFIG.SUPABASE_URL,
  SUPABASE_ANON_KEY: GENERATED_CONFIG.SUPABASE_ANON_KEY,
  ADMIN_EMAIL: GENERATED_CONFIG.ADMIN_EMAIL,
  EMAILJS_SERVICE_ID: GENERATED_CONFIG.EMAILJS_SERVICE_ID,
  EMAILJS_TEMPLATE_ID: GENERATED_CONFIG.EMAILJS_TEMPLATE_ID,
  EMAILJS_PUBLIC_KEY: GENERATED_CONFIG.EMAILJS_PUBLIC_KEY,
};

// Validate config
if (!CONFIG.SUPABASE_URL || !CONFIG.SUPABASE_ANON_KEY) {
  console.error('Supabase config is missing. Provide SUPABASE_URL and SUPABASE_ANON_KEY via Vercel environment variables.');
}

const { createClient } = supabase;
const supabaseClient = createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_ANON_KEY);

export { CONFIG, supabaseClient };
